// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hxrsvhqwagqzbcjrupzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh4cnN2aHF3YWdxemJjanJ1cHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3NDk3MzcsImV4cCI6MjA3MjMyNTczN30.6KIIVnPA3S6YhE3nCw-V_-Ml2JkZEwvsxPC7-ewzSiM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});